spring:
  application:
    name: pixiv
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:static/
server:
  port: 8084

custom:
  others:
    globalcookie: ${globalcookie}
    onproxy: 0
    pagesize: 30
    maxday: 3
    defcol: 3
    qqnum: ${qqnum}
    pushurl: ${pushurl}
  users:
    admin:
      password: ${password:password}
      cookie: ${mycookie}
    guest:
      password: ${guestpassword:password}
      cookie: ${globalcookie}
