spring:
  application:
    name: pixiv
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:static/
server:
  port: 8084

custom:
  others:
    globalcookie: ${globalcookie}
    onproxy: 0
    pagesize: 30
    maxday: 3
    defcol: 3
    qqnum: ${qqnum}
    pushurl: ${pushurl}
  users:
    leesin:
      password: ${password:password}
      cookie: ${mycookie}
    guest:
      password: ${guestpassword:password}
      cookie: ${globalcookie}
      #first_visit_datetime_pc=2023-01-08+17%3A01%3A40; p_ab_id=0; p_ab_id_2=7; p_ab_d_id=1873332630; yuid_b=NFVRclc; _gcl_au=1.1.932463366.1673164904; __utma=235335808.1572764744.1673164904.1673164905.1673164905.1; __utmc=235335808; __utmz=235335808.1673164905.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1; __cf_bm=TXJ7AmE.Kh4G91suE8qOsExdugiHUsyJj958ug7n6IU-1673164905-0-AdRFIH3CF8mM0199GdwS8N9cHei/LtToZJw6SjPLU7buzPOFiRFHW3+FZPrXNvA1eHJ01ANcjRTgPYDlAX3symI3AyY3CORym1TAFw9WkbpHQYQ4EUBpTg16qTRuqs63xFPghKkPTo5uL0Mkk3Zmb1X7R69IoJ1wCFcnoWSm+lqR+/Y9M6vc8+RreLXo7VXf04vauEDRSuA69UlpjrVQUHY=; _fbp=fb.1.1673164905784.1811069701; _gid=GA1.2.619239515.1673164915; _gat_UA-1830249-3=1; _gat_gtag_UA_76252338_1=1; PHPSESSID=89738068_F8xKLEZNgt3QpAmNazmFuLN1CW3BMCzj; device_token=2a102268fbabac5d32db6ecfa55b2db4; privacy_policy_agreement=5; _ga_MZ1NL4PHH0=GS1.1.1673164916.1.1.1673164929.0.0.0; c_type=23; privacy_policy_notification=0; a_type=0; b_type=1; __utmv=235335808.|2=login%20ever=no=1^3=plan=normal=1^5=gender=male=1^6=user_id=89738068=1^9=p_ab_id=0=1^10=p_ab_id_2=7=1^11=lang=zh=1; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0; _im_vid=01GP86DPG62ZBRBSH3EXBFR1DN; cto_bundle=NTC6HV8lMkYxWWF6UlJJQUhQYXF3SjBBRDhsODVrOEo3Vk9DekYyYnp3NTNwUXdlYWcwJTJCeldjcCUyQlIwejJtT3FDeDJzRVhnZW5vZVNDd1FpOWFLR1ElMkJWdUNBN3dlVk84NDNSQndkdXNwZGVnbURHRUFxOXo0UEh4QlhzRGdNcmVHdmpNZVByWTh6JTJCSEl3M096UGhIZmREcnFCdGdRJTNEJTNE; _ga_75BBYNYN9J=GS1.1.1673164904.1.1.1673164942.0.0.0; _ga=GA1.2.1572764744.1673164904; __utmb=235335808.3.10.1673164905
